version: '3.4'

services:
  emailsender.api:
    image: ${DOCKER_REGISTRY-}emailsenderapi
    build:
      context: .
      dockerfile: src/Services/EmailSender.API/Dockerfile

  smtp:
    container_name: smtp
    image: namshi/smtp
    restart: always
    networks:
      - blog-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    networks:
      - blog-network

  authentication.api:
    container_name: authentication-api
    image: ${DOCKER_REGISTRY-}authenticationapi
    restart: always
    depends_on:
      - authentication.db
    build:
      context: .
      dockerfile: src/Services/Authentication/Authentication.API/Dockerfile
    networks:
      - blog-network

  authentication.db:
    container_name: authentication-db
    image: mysql
    restart: always
    networks:
      - blog-network

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    networks:
      - blog-network
