version: '3.4'

volumes:
  authentication-db:

networks:
  blog-network:

services:
  emailsender.api:
    container_name: emailsender-api
    image: ${DOCKER_REGISTRY-}emailsenderapi
    restart: always
    depends_on: 
      - rabbitmq
      - smtp
    build:
      context: .
      dockerfile: src/Services/EmailSender.API/Dockerfile
    networks:
      - blog-network

  smtp:
    container_name: smtp
    image: namshi/smtp
    restart: always
    ports:
      - "25:25"
    networks:
      - blog-network

  authentication.api:
    container_name: authentication-api
    image: ${DOCKER_REGISTRY-}authenticationapi
    restart: always
    depends_on:
      - authentication.db
    build:
      context: .
      dockerfile: src/Services/Authentication/Authentication.API/Dockerfile
    ports:
      - "80:8001"
    networks:
      - blog-network

  authentication.db:
    container_name: authentication-db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: c6nZSU8d4VNT8rCw
    ports:
      - "3306:3306"
    volumes:
      - authentication-db:/var/lib/mysql
    networks:
      - blog-network

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    environment: 
      - PMA_HOST=authentication-db
    networks:
      - blog-network